// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAznoyPqS4o9vDe2AZ_xE759Fi9n6jpIFQ',
    appId: '1:1045083646577:web:46db038cf7fc3e6559c9d0',
    messagingSenderId: '1045083646577',
    projectId: 'predictive-net-405712',
    authDomain: 'predictive-net-405712.firebaseapp.com',
    storageBucket: 'predictive-net-405712.appspot.com',
    measurementId: 'G-7QT30CXZ93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArK_e8PVjbo_G64oPxgj0cMc6Y6TKRcPg',
    appId: '1:1045083646577:android:08e8339eb2544d7d59c9d0',
    messagingSenderId: '1045083646577',
    projectId: 'predictive-net-405712',
    storageBucket: 'predictive-net-405712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe50YePM_XwujjsrZo_Sa4n3gAmB8M-64',
    appId: '1:1045083646577:ios:8d533f0178e1d61f59c9d0',
    messagingSenderId: '1045083646577',
    projectId: 'predictive-net-405712',
    storageBucket: 'predictive-net-405712.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe50YePM_XwujjsrZo_Sa4n3gAmB8M-64',
    appId: '1:1045083646577:ios:245b24057b0e43f159c9d0',
    messagingSenderId: '1045083646577',
    projectId: 'predictive-net-405712',
    storageBucket: 'predictive-net-405712.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
